### PR TITLE
gtk4: React on device scale factor changes.

### PR DESCRIPTION
**Pull request by obyknovenius**
We're now tracking `GtkGLArea`'s scale factor and passing it to the backend every time it changes.

### CODE REVIEW

**Review by philn — APPROVED** [review]

**Comment by philn** [comment]
clang-format complains.

**Comment by obyknovenius** [comment]
clang-format mostly complained about '*'  positions of pointers. I've fixed that but now the new code is inconsistent with the existing one. Is that okay?

**Comment by philn** [comment]
> clang-format mostly complained about '*' positions of pointers. I've fixed that but now the new code is inconsistent with the existing one. Is that okay?

yes it's ok imho, but now some other CI build is failing and i have no clue about it... Paging @aperezdc ;)

**Comment by obyknovenius** [comment]
It doesn't look related:
```
curl: (18) transfer closed with 1445527151 bytes remaining to read
Download error (18), retrying download...
Waiting... 9 8 7 6 5 4 3 2 1 0.
Maximum amount of retries reached, bailing out.
```

**Comment by philn** [comment]
Maybe so but I'm not sure PR can be merged when the CI is broken.

**Comment by aperezdc** [comment]
Re-trying the CI jobs was enough to get them to pass. Turns out they had timed out trying to fetch the toolchain.

**Review by aperezdc — APPROVED** [review]

**Pull request merged**
