### PR TITLE
Update cursor on wl, x11 and gtk4

### PR DESCRIPTION
**Pull request by joantolo**
These changes allow the cursor to be updated when hovering on links or on input text fields. And the rest with the default pointer.

From a small conversation with @aperezdc on matrix, the idea was to create a signal at `WebKitWebView` and connect to it. However, the '`mouse-target-changed`' signal already gives some hovering mouse info, but not all. For instance, that signal doesn't inform when hovering over text.

As a first step, I've used '`mouse-target-changed`' signal.
A better signal could be emitted from `PageClientImpl::setCursor`. 
But when debugging cog, I see that `setCursor` isn't used, I don't know why.

The next step would be to use the `setCursor` to expose a signal with all cursor changes and add more cursor names. 

Fixes the cursor part of #594.

### CODE REVIEW

**Review by aperezdc — CHANGES_REQUESTED** [review]
@joantolo I have a couple of comments, could you please take a look? While at it, please use the `data/check-style` script to ensure the patch follows the same coding style as the rest of the source code.

Regarding the usage of the signal, I agree that it would be ideal to plumb WebKit's `PageClientImpl::setCursor()` instead to make it work for WPE; but that will need either new public API either in libwpe or in WPE WebKit itself, which would be way more effort.

In the meantime, I would be more than happy to have this implementation merged in Cog, because it's better than nothing. Thanks for working on this!

**Review by aperezdc — CHANGES_REQUESTED** [review]
@joantolo This is looking good, there's only one last detail before we can merge this: we need to add `libxcb-cursor-dev` in the list of packages to install during the CI builds, in `.github/workflows/ci-native.yml`.

If you could have a moment to rebase the patch and do that small change, then we can merge this. Thanks again!

**Comment by joantolo** [comment]
Added `libxcb-cursor-dev` and rebased.

**Review by aperezdc — APPROVED** [review]
Thanks @joantolo, this is now ready to merge!

**Pull request merged**
