### PR TITLE
CI: Publish docs on pushes to main branch

### PR DESCRIPTION
**Pull request by aperezdc**
Publishes the archived documentation artifacts after pushes to the main branch. Could be extended at some point for tags.

### CODE REVIEW

**Comment by aperezdc** [comment]
Here there are the auto-published pages: https://igalia.github.io/cog/

**Comment by aperezdc** [comment]
I've removed the `TODO` and now the publish step is only run for the main development branch. This is the intended behaviour (we don't want documentation builds from PRs clobbering the published documentation), and also the reason why the last test run on this PR skipped the step.

Now that this is working as intended, it is ready to merge once the PR is approved 😄

**Comment by aperezdc** [comment]
Ping reviewers 🏓

**Review by clopez — APPROVED** [review]

**Comment by aperezdc** [comment]
Thanks @clopez 🌠

**Pull request merged**
