### PR TITLE
Rename fdo platform plugin to wayland

### PR DESCRIPTION
**Pull request by Nasah-Kuma**

### CODE REVIEW

**Comment by philn** [comment]
Can you remove the "testing" commits please? That can be done with `git rebase -i`

**Comment by Nasah-Kuma** [comment]
> Can you remove the "testing" commits please? That can be done with `git rebase -i`

Done

**Comment by philn** [comment]
LGTM, thanks! CI is failing though ;) Can you rebase as well? Then we'd be good to go.

**Comment by philn** [comment]
Build fails: https://github.com/Igalia/cog/pull/351/checks?check_run_id=3388146576

**Comment by Nasah-Kuma** [comment]
> Build fails: https://github.com/Igalia/cog/pull/351/checks?check_run_id=3388146576

I'm a little confused as to why this error. I didn't change much from what was there initially

**Comment by philn** [comment]
> > Build fails: https://github.com/Igalia/cog/pull/351/checks?check_run_id=3388146576
> 
> I'm a little confused as to why this error. I didn't change much from what was there initially

Yeah, it's a bit odd indeed. And you can't reproduce this error locally I suppose?

**Comment by Nasah-Kuma** [comment]
> > > Build fails: https://github.com/Igalia/cog/pull/351/checks?check_run_id=3388146576
> > 
> > 
> > I'm a little confused as to why this error. I didn't change much from what was there initially
> 
> Yeah, it's a bit odd indeed. And you can't reproduce this error locally I suppose?

I get the error locally

**Review by philn — APPROVED** [review]

**Comment by Nasah-Kuma** [comment]
Does this need one more review before the issue can be closed?

**Review by aperezdc — APPROVED** [review]
I was actually checking this a bit some days ago, then forgot to actually go ahead and approve the PR 🤦🏼 

Let's go ahead with this. Thanks @Nasah-Kuma!

**Pull request merged**
