### PR TITLE
fdo: ensure xkb_data.state is not null before calling xkb_state_update_mask

### PR DESCRIPTION
**Pull request by jameshilliard**
Fixes:
```c
Thread 1 "cog" received signal SIGSEGV, Segmentation fault.
xkb_state_update_mask (state=0x0, base_mods=0, latched_mods=0, locked_mods=0, base_group=base_group@entry=0, latched_group=latched_group@entry=0, locked_group=0) at ../src/state.c:814
814	    prev_components = state->components;
```

### CODE REVIEW

**Comment by philn** [comment]
In which context did this crash happen, out of curiosity?

**Comment by jameshilliard** [comment]
I think this is happening since I didn't have a keyboard plugged in when running cog but not entirely sure.

Here's the backtrace:
```c
(gdb) bt
#0  xkb_state_update_mask (state=0x0, base_mods=0, latched_mods=0, locked_mods=0, base_group=base_group@entry=0, latched_group=latched_group@entry=0, locked_group=0) at src/state.c:812
#1  0x00007f3c8df6b8de in keyboard_on_modifiers (data=<optimized out>, wl_keyboard=<optimized out>, serial=<optimized out>, mods_depressed=<optimized out>, mods_latched=<optimized out>, mods_locked=<optimized out>, 
    group=0) at /home/buildroot/buildroot/output/build/cog-0.4.0/platform/cog-platform-fdo.c:865
#2  0x00007f3c8ec034e5 in ffi_call_unix64 () at ../src/x86/unix64.S:101
#3  0x00007f3c8ec02db7 in ffi_call_int (cif=cif@entry=0x7ffce69bb970, fn=0x7f3c8df6b8b5 <keyboard_on_modifiers>, rvalue=rvalue@entry=0x0, avalue=avalue@entry=0x7ffce69bb810, closure=closure@entry=0x0)
    at ../src/x86/ffi64.c:669
#4  0x00007f3c8ec03165 in ffi_call (cif=cif@entry=0x7ffce69bb970, fn=<optimized out>, rvalue=rvalue@entry=0x0, avalue=avalue@entry=0x7ffce69bb810) at ../src/x86/ffi64.c:688
#5  0x00007f3c8e7df3d6 in wl_closure_invoke (closure=0x7de000, flags=1, target=<optimized out>, opcode=4, data=<optimized out>) at src/connection.c:1014
#6  0x00007f3c8e7dd225 in dispatch_event (display=display@entry=0x671b00, queue=queue@entry=0x671bc8) at src/wayland-client.c:1430
#7  0x00007f3c8e7dd28b in dispatch_queue (display=display@entry=0x671b00, queue=queue@entry=0x671bc8) at src/wayland-client.c:1576
#8  0x00007f3c8e7ddc9d in wl_display_dispatch_queue_pending (display=0x671b00, queue=0x671bc8) at src/wayland-client.c:1818
#9  0x00007f3c8e7ddcbe in wl_display_dispatch_pending (display=<optimized out>) at src/wayland-client.c:1881
#10 0x00007f3c8df6c81b in wl_src_dispatch (base=base@entry=0x7d23a0, callback=<optimized out>, user_data=<optimized out>) at /home/buildroot/buildroot/output/build/cog-0.4.0/platform/cog-platform-fdo.c:218
#11 0x00007f3c91e64770 in g_main_dispatch (context=context@entry=0x652e90) at ../glib/gmain.c:3179
#12 0x00007f3c91e67139 in g_main_context_dispatch (context=context@entry=0x652e90) at ../glib/gmain.c:3844
#13 0x00007f3c91e672a1 in g_main_context_iterate (context=context@entry=0x652e90, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:3917
#14 0x00007f3c91e6731f in g_main_context_iteration (context=context@entry=0x652e90, may_block=may_block@entry=1) at ../glib/gmain.c:3978
#15 0x00007f3c92076553 in g_application_run (application=application@entry=0x64b8d0, argc=argc@entry=6, argv=argv@entry=0x7ffce69bbca8) at ../gio/gapplication.c:2559
#16 0x0000000000403205 in main (argc=6, argv=0x7ffce69bbca8) at /home/buildroot/buildroot/output/build/cog-0.4.0/cog.c:484
```

**Comment by philn** [comment]
No `wl_data.seat` either in `init_input()`?

**Comment by jameshilliard** [comment]
I assume that's the case but haven't checked specifically.

**Comment by jameshilliard** [comment]
Here's the logs from cog with this fix applied:
```
Feb 11 00:21:32 buildroot systemd[1]: Started WPE launcher and webapp container.
Feb 11 00:21:32 buildroot cog[280]: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
Feb 11 00:21:32 buildroot cog[280]: posix_spawn avoided (fd close requested) 
Feb 11 00:21:32 buildroot cog[280]: platform_setup: Platform name: fdo
Feb 11 00:21:32 buildroot cog[280]: platform_setup: Platform plugin: libcogplatform-fdo.so
Feb 11 00:21:32 buildroot cog[280]: Initializing Wayland...
Feb 11 00:21:32 buildroot cog[280]: Using 'wl_compositor' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Ignoring 'wl_subcompositor' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Ignoring 'wp_viewporter' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Ignoring 'zxdg_output_manager_v1' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Ignoring 'wp_presentation' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Ignoring 'zwp_relative_pointer_manager_v1' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Ignoring 'zwp_pointer_constraints_v1' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Ignoring 'zwp_input_timestamps_manager_v1' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Ignoring 'wl_data_device_manager' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Ignoring 'wl_shm' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Ignoring 'wl_drm' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Using 'wl_seat' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Ignoring 'zwp_linux_dmabuf_v1' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Ignoring 'weston_direct_display_v1' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Ignoring 'zwp_linux_explicit_synchronization_v1' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Ignoring 'weston_content_protection' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Using 'wl_output' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Using 'wl_output' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Ignoring 'zwp_input_panel_v1' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Ignoring 'zwp_input_method_v1' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Ignoring 'zwp_text_input_manager_v1' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Using 'xdg_wm_base' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Ignoring 'zxdg_shell_v6' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Using 'wl_shell' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Ignoring 'weston_desktop_shell' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Ignoring 'weston_screenshooter' interface obtained from the Wayland registry.
Feb 11 00:21:32 buildroot cog[280]: Initializing EGL...
Feb 11 00:21:33 buildroot cog[280]: EGL version 1.4 initialized.
Feb 11 00:21:33 buildroot cog[280]: Creating Wayland surface...
Feb 11 00:21:33 buildroot cog[280]: xkbcommon: ERROR: couldn't find a Compose file for locale "C"
Feb 11 00:21:33 buildroot cog[280]: platform_setup: Platform = 0x22c8d20
Feb 11 00:21:33 buildroot cog[280]: posix_spawn avoided (child_setup specified) 
Feb 11 00:21:33 buildroot cog[280]: posix_spawn avoided (child_setup specified) 
Feb 11 00:21:33 buildroot cog[280]: Enumerating seat capabilities:
Feb 11 00:21:33 buildroot cog[280]:   - Keyboard
Feb 11 00:21:33 buildroot cog[280]:   - Touch
Feb 11 00:21:33 buildroot cog[280]: Done enumerating seat capabilities.
Feb 11 00:21:33 buildroot cog[280]: Seat name: 'default'
Feb 11 00:21:33 buildroot cog[280]: Got scale factor 1 for output 0x22dfed0
Feb 11 00:21:33 buildroot cog[280]: Got scale factor 1 for output 0x22dff50
Feb 11 00:21:33 buildroot cog[280]: New XDG toplevel configuration: (1280, 1024)
Feb 11 00:21:33 buildroot cog[280]: Resized EGL buffer to: (1280, 1024) @1x
Feb 11 00:21:33 buildroot WPENetworkProce[308]: Failed to initialize portal (GNetworkMonitorPortal) for gio-network-monitor: Not using portals
Feb 11 00:21:33 buildroot WPEWebProcess[307]: posix_spawn avoided (fd close requested) 
Feb 11 00:21:34 buildroot WPENetworkProce[308]: _g_io_module_get_default: Found default implementation networkmanager (GNetworkMonitorNM) for ‘gio-network-monitor’
Feb 11 00:21:34 buildroot WPENetworkProce[308]: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
Feb 11 00:21:35 buildroot cog[280]: Surface entered output 0x22dfed0 with scale factor 1
Feb 11 00:21:35 buildroot cog[280]: New XDG toplevel configuration: (1280, 1024)
Feb 11 00:21:35 buildroot cog[280]: Resized EGL buffer to: (1280, 1024) @1x
Feb 11 00:21:35 buildroot cog[280]: <file:///> Load started.
Feb 11 00:21:35 buildroot cog[280]: <file:///> Loading...
Feb 11 00:21:36 buildroot cog[280]: <file:///> Loaded successfully.
Feb 11 00:21:36 buildroot WPENetworkProce[308]: _g_io_module_get_default: Found default implementation dummy (GDummyProxyResolver) for ‘gio-proxy-resolver’
Feb 11 00:21:36 buildroot WPENetworkProce[308]: _g_io_module_get_default: Found default implementation dummy (GDummyTlsBackend) for ‘gio-tls-backend’
```

**Comment by aperezdc** [comment]
Merged to the `cog-0.4` branch as commit a0a520337e7411644727c9423ffde4b87d3bf965 — thanks @jameshilliard!

**Pull request merged**
