### PR TITLE
drm: implement keyboard event repeating when the key remains pressed

### PR DESCRIPTION
**Pull request by kytart**
inspired by wpebackend-rdk https://github.com/WebPlatformForEmbedded/WPEBackend-rdk/blob/master/src/input/Libinput/KeyboardEventRepeating.cpp

### CODE REVIEW

**Review by aperezdc — CHANGES_REQUESTED** [review]
Hi @kytart! Thanks for the patch, the logic looks good.

I only have a few comments about code style. I know that it can feel like a drag to take care of those, but it's better in the long run for maintanability. Could you take a look at the comments?

**Comment by kytart** [comment]
@aperezdc I pushed the changes that you suggested. Have a look now pls :)

**Review by aperezdc — APPROVED** [review]
This patch looks good as well, and again the WebKitGTK CI build failure is not relevant anymore after #257 — let's get this merged!

Thanks a lot to @kytart for the patch and his patience waiting for me to come back to re-review this :innocent:

**Comment by kytart** [comment]
@aperezdc Amazing! Thanks for coming back to it :)

**Pull request merged**
