### PR TITLE
core: When guess input URIs, directly use valid ones

### LINKED ISSUE #75: Silently fails to load URIs containing authentication credentials
Use-case: `cog -P fdo http://foo:password@example.com`
Expected behavior: Page displays
Current behavior: White page

The problem is that in `cog_uri_guess_from_user_input` we use `soup_uri_to_string()` which, as documented, strips the password out.

### PR DESCRIPTION
**Pull request by aperezdc**
Change the `cog_uri_guess_from_user_input()` function slightly, so if an input URI is valid and the scheme refers to a network protocol, use the passed string directly, decoded from the command line locale. This avoids converting the `SoupURI` resulting from parsing to a string, which is what caused passwords in URIs to be stripped out.

Fixes #75

### CODE REVIEW

**Comment by carlosgcampos** [comment]
g_file_new_for_commandline_arg() does resolve relative paths.

**Comment by aperezdc** [comment]
@carlosgcampos True, but it still won't resolve `file:foo` and `file://foo` to `file://$(pwd)/foo` :upside_down_face:

**Comment by philn** [comment]
Ping :)

**Comment by aperezdc** [comment]
Updated. I tried to keep it as simple as possible, but there are still a few cases for which `GFile` is not enough. There are now a coupl of comments in the code explaining that.

**Comment by philn** [comment]
I tested this new version, 👍

**Pull request merged**
